version: 0.0
os: linux
files:
	- source: /
  	destination: /home/ec2-user/github_action
	overwrite: yes

permissions:
	- object: /
	  pattern: "**"
	  owner: Amazon Linux
	  group: Amazon Linux

hooks:
	ApplicationStart:
	  - location: scripts/gh_deploy.sh
	  timeout: 60
	  runas: Amazon Linux
